version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: todobot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 26221030
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
